export const adminUi = {
  pageContainer: "max-w-6xl mx-auto px-4 sm:px-6 pt-6 lg:pt-10 space-y-6 lg:space-y-10 relative z-10",
  /** NFC 하위 페이지 본문: 상단 sticky 서브네비보다 아래 레이어에 두어 탭과 제목이 겹쳐 보이지 않게 함 */
  nfcTagsPageBody: "max-w-6xl mx-auto px-4 sm:px-6 pt-6 lg:pt-10 space-y-6 lg:space-y-10 relative z-0",
  sectionCard: "bg-white border-slate-100 rounded-[40px] p-8 shadow-xl",
  kpiCard: "bg-white border-slate-100 rounded-3xl p-5 shadow-md",
  subtleCard: "bg-white border-slate-100 shadow-md rounded-2xl",
  input: "h-10 rounded-xl border border-slate-200 bg-slate-50 text-xs font-bold text-slate-700 px-3 outline-none",
  searchInput: "w-full h-12 bg-slate-50 border border-slate-200 rounded-2xl pl-12 pr-4 text-xs font-bold text-slate-700 focus:ring-2 focus:ring-teal-500/20 transition-all outline-none",
  outlineButton: "border-slate-200 bg-white text-slate-700 hover:bg-slate-50",
  darkButton: "bg-slate-900 hover:bg-teal-500 text-white font-black transition-all active:scale-95 shadow-xl",
  tableHeadRow: "border-b border-slate-100",
  tableHeadCell: "py-4 px-4 text-[10px] font-black text-slate-500 uppercase tracking-[0.16em]",
  tableRowHover: "hover:bg-slate-50 transition-colors",
  tableBodyCell: "py-4 px-4 text-[11px] font-bold text-slate-600",
  tableBodyCellStrong: "py-4 px-4 text-[11px] font-bold text-slate-900",
  tableBodyCellMono: "py-4 px-4 text-[11px] font-mono font-bold text-slate-700",
  successBadge: "bg-teal-50 text-teal-600 border-teal-200",
  dangerBadge: "bg-rose-50 text-rose-600 border-rose-200",
  warningBadge: "bg-amber-50 text-amber-600 border-amber-200",
  neutralBadge: "bg-slate-100 text-slate-600 border-transparent",
};
